@Starbucks.MenuManager.API_HostAddress = http://localhost:5088

GET {{Starbucks.MenuManager.API_HostAddress}}/api/Category
Accept: application/json

###

POST {{Starbucks.MenuManager.API_HostAddress}}/api/Coffe
Accept: application/json
Content-Type: application/json

{
  "name": "",
  "description": "",
  "price": 0,
  "categoryId": 1,
  "imagen": ""
}

###
