// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Starbucks.MenuManager.API.Persistence.Contexts;

#nullable disable

namespace Starbucks.MenuManager.API.Persistence.Migrations
{
    [DbContext(typeof(StarbucksDbContext))]
    [Migration("20260504174636_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("Starbucks.MenuManager.API.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IceCoffe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HotCoffe"
                        });
                });

            modelBuilder.Entity("Starbucks.MenuManager.API.Domain.Entities.Coffe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Imagen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Coffes");
                });

            modelBuilder.Entity("Starbucks.MenuManager.API.Domain.Entities.CoffeIngredient", b =>
                {
                    b.Property<Guid>("CoffeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("TEXT");

                    b.HasKey("CoffeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("CoffeIngredient");
                });

            modelBuilder.Entity("Starbucks.MenuManager.API.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Starbucks.MenuManager.API.Domain.Entities.Coffe", b =>
                {
                    b.HasOne("Starbucks.MenuManager.API.Domain.Entities.Category", "Category")
                        .WithMany("Coffes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Starbucks.MenuManager.API.Domain.Entities.CoffeIngredient", b =>
                {
                    b.HasOne("Starbucks.MenuManager.API.Domain.Entities.Coffe", "Coffe")
                        .WithMany("CoffeIngredients")
                        .HasForeignKey("CoffeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Starbucks.MenuManager.API.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("CoffeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coffe");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Starbucks.MenuManager.API.Domain.Entities.Category", b =>
                {
                    b.Navigation("Coffes");
                });

            modelBuilder.Entity("Starbucks.MenuManager.API.Domain.Entities.Coffe", b =>
                {
                    b.Navigation("CoffeIngredients");
                });

            modelBuilder.Entity("Starbucks.MenuManager.API.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("CoffeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
